image: python:3.7.4-alpine3.10
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - apk add --update --no-cache openssh git
          - git push git@github.com:genropy/genropy.git

  tags:
    ecr-release-*:
      - step:
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="public.ecr.aws/genropy/genropy"
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/genropy
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG