image: python:3.7.4-alpine3.10
clone:
  depth: full

definitions:
  services:
    postgres:
     image: postgres
     environment:
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       DATABASE_URL: postgres://postgres@127.0.0.1:5432/postgres
  
pipelines:
  default:
    - step:
        script:
          - apk add --update --no-cache openssh git
          - git push git@github.com:genropy/genropy.git
  branches:
    develop:
      - parallel:
          steps:
            - step:
                name: Tests against python 3.8
                image: python:3.8-bookworm
                caches:
                  - pip
                script:
                  - cd gnrpy
                  - pip install --editable .[developer]
                  - cd tests
                  - pytest core sql web app xtnd
                services:
                  - postgres
                  
            - step:
                name: Tests against python 3.9
                image: python:3.9-bookworm
                caches:
                  - pip
                script:
                  - cd gnrpy
                  - pip install --editable .[developer]
                  - cd tests
                  - pytest core sql web app xtnd
                services:
                  - postgres
                  
            - step:
                name: Tests against python 3.10
                image: python:3.10-bookworm
                caches:
                  - pip
                script:
                  - cd gnrpy
                  - pip install --editable .[developer]
                  - cd tests
                  - pytest core sql web app xtnd
                services:
                  - postgres

            - step:
                name: Tests against python 3.11
                image: python:3.11-bookworm
                caches:
                  - pip
                script:
                  - cd gnrpy
                  - pip install --editable .[developer]
                  - cd tests
                  - pytest core sql web app xtnd
                services:
                  - postgres

            - step:
                name: Tests against python 3.12
                image: python:3.12.1-bookworm
                caches:
                  - pip
                script:
                  - apt update && apt install -y locales-all
                  - cd gnrpy
                  - pip install --editable .[developer]
                  - cd tests
                  - LC_ALL="en_US" GNR_LOCALE="en_US" pytest core sql web app xtnd
                services:
                  - postgres
                  
  tags:
    ecr-release-*:
      - step:
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="public.ecr.aws/x2x6r1v6/genropy"
            - TAG=${BITBUCKET_TAG:12}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x2x6r1v6
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG
