"""
executor.py - Assembly and execution of SQL migration commands
================================================================

This module contains the :class:`ExecutorMixin`, responsible for:

1. **Assembling** the SQL commands generated by the command builders into
   a single executable SQL string, with the correct ordering.

2. **Executing** the SQL commands on the database via the adapter.

3. **Verifying** type conversions with backup to detect
   potential data loss.

Command ordering
-----------------

Assembly follows a specific order to respect dependencies::

    1. CREATE DATABASE (if the DB doesn't exist)
    2. CREATE EXTENSION (required extensions)
    3. CREATE SCHEMA (new schemas)
    4. For each table:
       a. Pre-commands (column backups for type conversions)
       b. CREATE TABLE (new tables) or ALTER TABLE (columns)
       c. ADD CONSTRAINT (UNIQUE, CHECK constraints)
       d. CREATE INDEX (indexes)
    5. ALTER TABLE ADD FOREIGN KEY (FK relations - last)

**Foreign keys are applied last** because they might reference
tables created in the same migration. If they were applied before
the target tables were created, they would fail.

Execution modes
----------------

The ``applyChanges()`` method executes commands in three phases:

1. **db_creation**: executed with ``manager=True`` (uses the system
   connection, not the connection to the DB being created)

2. **build_commands**: executed with ``autoCommit=True`` (each statement
   is committed immediately, without an atomic transaction)

3. **extensions_commands**: executed with ``autoCommit=True``

Backup conversion verification
-------------------------------

When the ``--backup`` flag is used for type conversions,
the ``verifyConversionBackups()`` method checks for data loss
by comparing the converted column with the backup:

- If ``backup_column IS NOT NULL AND column IS NULL``: data lost
- If no loss: the backup column is automatically removed
- If there is loss: the backup column is preserved and a
  report is generated for the user
"""


from gnr.sql._typing import SqlMigratorBaseMixin


class ExecutorMixin(SqlMigratorBaseMixin):
    """Mixin providing assembly and execution of SQL commands.

    This mixin is composed into the :class:`SqlMigrator` class and
    requires the host to have these attributes:
    - ``commands``: defaultdict with commands generated by the builders
    - ``sql_commands``: dictionary for assembled SQL commands
    - ``db``: database object with ``db.adapter``
    """

    def getChanges(self):
        """Assemble all SQL commands and return them as a string.

        This is the main method for obtaining the migration SQL
        without executing it. Useful for:
        - Viewing changes before applying them
        - Saving the SQL script for review
        - Manual execution

        The method:
        1. Calls ``prepareMigrationCommands()`` if not already done
        2. Extracts DB creation and extension commands
        3. Iterates over schemas and tables assembling commands
        4. Adds FKs last

        Returns:
            str: All SQL commands concatenated with newlines.
        """
        if 'db' not in self.commands:
            self.prepareMigrationCommands()
        commands = self.commands
        dbitem = commands['db']
        sql_command = dbitem.get('command')
        schemas = dbitem.get('schemas', {})
        extensions_sql_commands = [
            extension['command']
            for extension in dbitem['extensions'].values()
        ]

        # Save the DB creation command if present
        if sql_command:
            self.sql_commands['db_creation'] = sql_command
        if extensions_sql_commands:
            self.sql_commands['extensions_commands'] = '\n'.join(
                extensions_sql_commands
            )

        command_list = []
        relation_command_list = []

        # Process each schema
        for schema_name, schema_item in schemas.items():
            schema_command = schema_item.get('command')
            tables = schema_item.get('tables', {})

            if schema_command:
                command_list.append(schema_command)

            # Process each table in the schema
            for table_name, tbl_item in tables.items():
                table_commands = self.sqlCommandsForTable(
                    schema_name=schema_name,
                    table_name=table_name,
                    tbl_item=tbl_item
                )
                command_list += table_commands['commands']
                relation_command_list += table_commands['relation_commands']

        # FKs are added last to respect dependencies
        command_list += relation_command_list
        self.sql_commands['build_commands'] = '\n'.join(command_list)

        return '\n'.join([v for v in self.sql_commands.values() if v])

    def sqlCommandsForTable(self, schema_name=None, table_name=None,
                            tbl_item=None):
        """Assemble SQL commands for a single table.

        Handles both the case of a new table (CREATE TABLE) and an
        existing table to modify (ALTER TABLE with ADD/ALTER COLUMN).

        The assembly order is:
        1. Pre-commands (column backups for conversions)
        2. CREATE TABLE (new table) or ALTER TABLE with columns
        3. ADD CONSTRAINT (separate constraints)
        4. CREATE INDEX (separate indexes)

        Foreign keys are returned separately in ``relation_commands``
        to be applied last.

        Args:
            schema_name: Name of the schema.
            table_name: Name of the table.
            tbl_item: Table command dictionary from the command builder.

        Returns:
            dict: With keys ``commands`` (list of SQL) and
            ``relation_commands`` (list of SQL for FKs).
        """
        command_list = []
        relation_command_list = []
        alter_table_command = f'ALTER TABLE "{schema_name}"."{table_name}"'

        # Pre-commands: column backups before type conversions
        pre_commands = tbl_item.get('pre_commands', [])
        for pre_cmd in pre_commands:
            command_list.append(f"{pre_cmd};")

        # Columns: all column commands are combined into a single
        # ALTER TABLE with commas
        col_commands = ',\n'.join(
            col['command'] for col in tbl_item['columns'].values()
        )
        constraint_commands = [
            con['command'] for con in tbl_item['constraints'].values()
        ]

        # FK: each relation becomes a separate ALTER TABLE
        relation_command_list += [
            f"{alter_table_command}\n {rel['command']};"
            for rel in tbl_item['relations'].values()
        ]

        table_command = tbl_item.get('command')
        if table_command:
            # New table: the command is the complete CREATE TABLE
            command_list.append(table_command)
        elif col_commands:
            # Existing table: ALTER TABLE with all columns
            command_list.append(f"{alter_table_command}\n{col_commands};")

        # Separate constraints: each constraint needs its own ALTER TABLE
        for constraint_sql in constraint_commands:
            command_list.append(f"{alter_table_command}\n{constraint_sql};")

        # Indexes: standalone commands (CREATE INDEX doesn't use ALTER TABLE)
        command_list += [
            idx['command'] for idx in tbl_item['indexes'].values()
        ]

        return {
            "commands": command_list,
            "relation_commands": relation_command_list
        }

    def applyChanges(self):
        """Execute the SQL migration commands on the database.

        Calls ``getChanges()`` to assemble the commands, then executes
        them in three separate phases:

        1. **db_creation**: CREATE DATABASE, executed with ``manager=True``
           (uses the system connection, not the one to the DB being created)

        2. **build_commands**: CREATE SCHEMA, CREATE/ALTER TABLE, CREATE INDEX,
           ADD CONSTRAINT, ADD FOREIGN KEY. Executed with ``autoCommit=True``.

        3. **extensions_commands**: CREATE EXTENSION. Executed with
           ``autoCommit=True``.
        """
        self.getChanges()

        db_creation = self.sql_commands.pop('db_creation', None)
        if db_creation:
            self.db.adapter.execute(db_creation, manager=True)

        extensions_commands = self.sql_commands.pop('extensions_commands', None)
        if extensions_commands:
            self.db.adapter.execute(extensions_commands, autoCommit=True)

        build_commands = self.sql_commands.pop('build_commands', None)
        if build_commands:
            self.db.adapter.execute(build_commands, autoCommit=True)

    def verifyConversionBackups(self):
        """Verify backup columns after type conversions.

        After a migration with ``--backup``, this method checks
        each backup column for data loss:

        - **No loss** (all values converted correctly):
          the backup column is automatically dropped.

        - **Loss detected** (values that were non-NULL are now NULL):
          the backup column is preserved and the report includes the
          number of lost values and the backup column name.

        - **Error during verification**: the backup column is
          preserved for safety.

        Returns:
            dict: Report of conversions with data loss. Keys in the
            format ``schema.table.column``, values with ``lost_values``,
            ``backup_column``, ``conversion``, ``message``.
            Empty dictionary if no loss or no backups.
        """
        if not hasattr(self, '_conversion_backups') or not self._conversion_backups:
            return {}

        data_loss_report = {}

        for backup_info in self._conversion_backups:
            schema = backup_info['schema']
            table = backup_info['table']
            column = backup_info['column']
            backup_column = backup_info['backup_column']
            old_dtype = backup_info['old_dtype']
            new_dtype = backup_info['new_dtype']

            full_table = f'"{schema}"."{table}"'

            # Count lost values: backup non-NULL but converted column NULL
            check_sql = f'''
                SELECT COUNT(*) FROM {full_table}
                WHERE "{backup_column}" IS NOT NULL AND "{column}" IS NULL
            '''

            try:
                result = self.db.execute(check_sql)  # REVIEW: uses db.execute instead of db.adapter.execute — inconsistent API
                row = result.fetchone() if result else None
                lost_count = row[0] if row else 0

                if lost_count > 0:
                    # Data loss: preserve backup and report
                    data_loss_report[f'{schema}.{table}.{column}'] = {
                        'lost_values': lost_count,
                        'backup_column': backup_column,
                        'conversion': f'{old_dtype} -> {new_dtype}',
                        'message': (
                            f'WARNING: {lost_count} value(s) could not be '
                            f'converted. Original data preserved in column '
                            f'"{backup_column}".'
                        )
                    }
                else:
                    # No loss: remove backup
                    drop_sql = (
                        f'ALTER TABLE {full_table} '
                        f'DROP COLUMN "{backup_column}"'
                    )
                    self.db.adapter.execute(drop_sql, autoCommit=True)

            except Exception as e:  # REVIEW: bare except catches everything — should narrow to specific DB exceptions
                # On error, preserve backup for safety
                data_loss_report[f'{schema}.{table}.{column}'] = {
                    'error': str(e),
                    'backup_column': backup_column,
                    'message': (
                        f'Could not verify conversion. Backup column '
                        f'"{backup_column}" preserved.'
                    )
                }

        self._conversion_backups = []
        return data_loss_report
