# -*- coding: utf-8 -*-

"""Hand-built form: load, save and reload a record without a TableHandler

This page is not a TestHandler page: it overrides main() and builds the whole
form by hand. It shows the plumbing a form needs when it is not generated by a
TableHandler — a formId, a controllerPath, a pkeyPath, and the two dataRpc
calls that load and save the record around them.
"""


class GnrCustomWebPage(object):
    py_requires = 'public'

    def main(self, rootBC, **kwargs):
        """Build the page: a record picker on top of a two-field form"""
        # `public_rootBorderContainer` is a @struct_method: it is called on the struct
        # node, not on the page, and it returns the frame. The page-method form this
        # line used to call (`self.pbl_rootBorderContainer`) was removed from
        # resources/common/public.py in 2012, so the page raised AttributeError ever
        # since. The frame's center is a plain slot, hence the explicit
        # borderContainer that gives the two regions below a layout.
        frame = rootBC.rootBorderContainer(title="!!Province", margin="1em", **kwargs)
        center = frame.center.borderContainer()

        btPane = center.contentPane(region="bottom")
        buttons = btPane.div(width="100%")
        buttons.dbselect(value="^scheda.loadingPkey", dbtable="glbl.provincia")
        buttons.dataController(
                """genro.formById('miaForm').load({destPkey:newPkey,cancelCb:function(){genro.setData("scheda.loadingPkey",oldPkey)}})"""
                ,
                newPkey='^scheda.loadingPkey', oldPkey='=scheda.pkey',
                _if='newPkey!=oldPkey')
        buttons.button('Save', float="right", action="genro.formById('miaForm').save(); ")

        cp = center.contentPane(region="center", formId="miaForm", datapath="scheda.dati", controllerPath="scheda.form",
                                pkeyPath="scheda.pkey")
        fb = cp.formbuilder(cols=2, border_spacing='4px', width="100%", fld_width="100%")
        fb.textbox(value="^.sigla", lbl="Sigla", validate_notnull=True)
        fb.textbox(value="^.nome", lbl="Nome", validate_notnull=True)

        cp.dataRpc('scheda.dati', 'caricaDati', nodeId="miaForm_loader", pkey="=scheda.pkey",
                   _onResult="genro.formById('miaForm').loaded()")
        cp.dataRpc('dummy', 'salvaDati', nodeId="miaForm_saver", dati="=scheda.dati",
                   _onResult="genro.formById('miaForm').saved(); genro.formById('miaForm').load();")

    def rpc_caricaDati(self, pkey, **kwargs):
        """Return the selected province as a Bag, the shape the form expects"""
        return self.db.table('glbl.provincia').recordAs(pkey, 'bag')

    def rpc_salvaDati(self, dati, **kwargs):
        """Receive the edited record; this demo prints it instead of writing it"""
        print("Saved data:")
        print(dati)
