// Rebuild the compatibility inventory from both executable prototype chains.
const fs = require('node:fs');
const path = require('node:path');
const {loadPair} = require('./bag_audit_harness.cjs');
const {legacy, selected} = loadPair();
const classes = ['GnrBag','GnrBagNode','GnrBagResolver','GnrBagFormula',
    'GnrBagGetter','GnrBagCbResolver','GnrDomSource','GnrDomSourceNode'];
function members(klass) {
    const result = new Map();
    for (let p = klass.prototype; p && Object.getPrototypeOf(p); p=Object.getPrototypeOf(p)) {
        for (const key of Object.getOwnPropertyNames(p)) {
            if (!result.has(key)) result.set(key, Object.getOwnPropertyDescriptor(p,key));
        }
    }
    return result;
}
function signature(descriptor) {
    if (!descriptor) return 'missing';
    if (typeof descriptor.value !== 'function') return descriptor.get ? 'getter' : typeof descriptor.value;
    const source = descriptor.value.toString();
    return source.slice(0,source.indexOf('{')).replace(/\s+/g,' ').trim();
}
const records=[];
for (const name of classes) {
    const a=members(legacy.gnr[name]),b=members(selected.gnr[name]);
    for (const [method,d] of a) records.push({class:name,member:method,
        legacy:signature(d),selected:signature(b.get(method)),available:b.has(method),
        sameBody:b.has(method) && typeof d.value==='function' && d.value.toString()===b.get(method).value?.toString()});
}
const destination=path.join(__dirname,'../../docs/bag-audit');
fs.mkdirSync(destination,{recursive:true});
fs.writeFileSync(path.join(destination,'surface.json'),JSON.stringify(records,null,2)+'\n');
const lines=['# Executable API inventory','','Generated by `node gnrjs/tests/bag_audit_inventory.cjs`.',
    'Presence and matching function bodies are structural evidence, not proof of all runtime behavior.',
    'Inherited members are included for each class. See the semantic audit reports and differential tests.','',
    '| Class | Member | Legacy signature | Selected signature | Available |',
    '| --- | --- | --- | --- | --- |'];
// Escape backslashes before pipes so a table cell cannot break out of its column.
const cell=(text)=>text.replace(/\\/g,'\\\\').replace(/\|/g,'\\|');
for (const r of records) lines.push(`| ${r.class} | ${r.member} | \`${cell(r.legacy)}\` | \`${cell(r.selected)}\` | ${r.available?'yes':'NO'} |`);
fs.writeFileSync(path.join(destination,'surface.md'),lines.join('\n')+'\n');
console.log(JSON.stringify({entries:records.length,missing:records.filter(r=>!r.available).map(r=>r.class+'.'+r.member)}));
