#!/usr/bin/env python
# encoding: utf-8

from gnr.lib.services.rms import RMS
from optparse import OptionParser
from gnr.app.gnrconfig import getRmsOptions,setRmsOptions
from gnr.app.gnrconfig import updateGnrEnvironment
from gnr.core.gnrbag import Bag
from gnr.app.gnrdeploy import PathResolver
import os


def main(instance,**kwargs):
    rms = RMS()
    rms.registerInstance(instance,**kwargs)

def init_env(pod=None, service_url=None):
    setRmsOptions(code=pod, url=service_url)

if __name__ == '__main__':
    usage = """

    """

    parser = OptionParser(usage)
    parser.add_option('--pod','-p',
                dest='pod',
                help="Pod")
    parser.add_option('--service_url',
                dest='service_url',
                help="Service url")
    parser.add_option('--domain','-d',
                dest='domain',
                help="Domain")
    parser.add_option('--customer_code','-c',
                dest='customer_code',
                help="Customer Code")

    (options, args) = parser.parse_args()
    instance = args[0] if args else None
    if instance:
        main(instance,domain=options.domain, customer_code=options.customer_code)
    else:
        pod = options.pod
        service_url = options.service_url or "https://deploy.softwell.it/deploy/rms_endpoint"
        if pod:
            init_env(pod=pod, service_url=service_url)
        else:
            print('Missing pod code')