#!/usr/bin/env python
# encoding: utf-8
# 

from gnr.web.gnrtask import GnrTaskScheduler
import argparse

 
def getOptions():
    usage = "\ngnrtaskworker sitename"
    parser = argparse.ArgumentParser(usage)
    parser.add_argument('sitename')
    arguments= parser.parse_args()
    return arguments.__dict__


if __name__=="__main__":
    options = getOptions()
    sitename = options.pop('sitename')
    interval = options.pop('interval',None)
    w = GnrTaskScheduler(sitename,interval=interval)
    w.start()