"""Tests for the conf.py generated by the export_to_sphinx batch.

The sphinx features driven by the docu preferences are implemented by
sphinx extensions: the sitemap file is written by sphinx_sitemap and the
opengraph meta tags by sphinxext.opengraph. Their config values
(sitemap_url_scheme, ogp_image) do nothing unless the extension itself is
listed in `extensions`, so the batch has to write that assignment in the
generated conf.py, and the sitemap has to appear in a real build.

The tests need no running site: they build a throwaway application on a
temporary sqlite file, expose real local storage services on temporary
directories (the docu resources included, so the shipped default_conf.py
is the one being extended) and run the actual sphinx build on the result.
"""
import os
import shutil
import tempfile
from types import SimpleNamespace

import pytest

from gnr.core.gnrbag import Bag
from gnr.core.gnrlang import gnrImport
from gnr.lib.services.storage import BaseLocalService, StorageNode

from core.common import BaseGnrAppTest

INSTANCE_HOST = 'https://instance.example.org'
BASE_URL = 'https://docs.example.org/_documentation/'
HANDBOOK_NAME = 'testhandbook'


class StorageSiteStub:
    """Minimal site wiring exposing real local storage services to the batch."""

    def __init__(self, services_dirs):
        self.external_host = INSTANCE_HOST
        self.currentPage = SimpleNamespace(isMobile=False, user=None)
        self.services = {}
        for name, base_path in services_dirs.items():
            service = BaseLocalService(parent=self, base_path=base_path)
            service.service_name = name
            self.services[name] = service

    def storageNode(self, fullpath, *parts):
        if isinstance(fullpath, StorageNode):
            return fullpath
        if parts:
            fullpath = '/'.join([fullpath] + list(parts))
        service_name, path = fullpath.split(':', 1)
        return StorageNode(parent=self, path=path, service=self.services[service_name])

    def externalUrl(self, url, **kwargs):
        return '%s%s' % (INSTANCE_HOST, url)


class TestDocuSphinxConf(BaseGnrAppTest):

    @classmethod
    def setup_class(cls):
        super().setup_class()
        cls.db = cls.app.db
        cls.db.model.check(applyChanges=True)
        cls.site_dir = tempfile.mkdtemp(prefix='gnr_docu_sphinx_site_')
        cls.rsrc_dir = tempfile.mkdtemp(prefix='gnr_docu_sphinx_rsrc_')
        #the batch reads the shipped resources as 'rsrc:pkg_docu': link the real folder
        os.symlink(os.path.join(cls.app.packages['docu'].packageFolder, 'resources'),
                   os.path.join(cls.rsrc_dir, 'pkg_docu'))
        cls.app.site = StorageSiteStub({'site': cls.site_dir, 'rsrc': cls.rsrc_dir})

    @classmethod
    def teardown_class(cls):
        for folder in (cls.site_dir, cls.rsrc_dir):
            shutil.rmtree(folder, ignore_errors=True)
        super().teardown_class()

    def _batch(self, enable_sitemap=None, ogp_image=None, subfolder='conf'):
        pytest.importorskip('sphinx')
        module_path = os.path.join(self.app.packages['docu'].packageFolder,
                                   'resources', 'tables', 'handbook', 'action',
                                   'export_to_sphinx.py')
        module = gnrImport(module_path, avoidDup=True)
        page = SimpleNamespace(db=self.db, btc=None, site=self.app.site,
                               external_host=INSTANCE_HOST,
                               getUuid=lambda: 'test-batch')
        batch = module.Main(page=page, resource_table=self.db.table('docu.handbook'))
        batch.handbook_record = Bag(dict(name=HANDBOOK_NAME, theme=None,
                                         version='1.0', ogp_image=ogp_image))
        batch.enable_sitemap = enable_sitemap
        batch.html_baseurl = BASE_URL
        batch.sourceDirNode = self.app.site.storageNode('site:%s' % subfolder, 'source')
        return batch

    def _confSource(self, **kwargs):
        batch = self._batch(**kwargs)
        batch.step_prepareConfFile()
        with batch.sourceDirNode.child('conf.py').open('r') as conf_file:
            return conf_file.read()

    def _confValues(self, source):
        """Return the config values conf.py actually defines, reading it the way
        sphinx does: the last assignment of a name is the one that counts"""
        namespace = {}
        exec(compile(source, 'conf.py', 'exec'), namespace)
        return namespace

    def test_sitemap_preference_enables_the_extension(self):
        """The sitemap preference has to add sphinx_sitemap to the extensions:
        the url scheme alone is a config value nothing reads"""
        conf = self._confValues(self._confSource(enable_sitemap=True,
                                                 subfolder='sitemap_on'))
        assert 'sphinx_sitemap' in conf['extensions']
        assert conf['sitemap_url_scheme'] == '%s/{link}' % HANDBOOK_NAME
        assert conf['html_baseurl'] == BASE_URL

    def test_sitemap_preference_disabled(self):
        conf = self._confValues(self._confSource(enable_sitemap=False,
                                                 subfolder='sitemap_off'))
        assert 'sphinx_sitemap' not in conf['extensions']
        assert 'sitemap_url_scheme' not in conf

    def test_ogp_image_enables_the_opengraph_extension(self):
        """ogp_image is passed to sphinx-build as a config value of
        sphinxext.opengraph, which has to be loaded to read it"""
        conf = self._confValues(self._confSource(enable_sitemap=True,
                                                 ogp_image='/media/preview.png',
                                                 subfolder='ogp_on'))
        assert conf['extensions'] == ['sphinx_sitemap', 'sphinxext.opengraph']

    def test_no_ogp_image_leaves_opengraph_out(self):
        conf = self._confValues(self._confSource(enable_sitemap=True,
                                                 subfolder='ogp_off'))
        assert 'sphinxext.opengraph' not in conf['extensions']

    def test_missing_extension_is_skipped(self):
        """An extension missing from the environment is dropped instead of
        aborting the whole build with an ExtensionError"""
        batch = self._batch(subfolder='missing')
        assert batch.installedSphinxExtensions(
            ['sphinx_sitemap', 'no_such_sphinx_extension']) == ['sphinx_sitemap']

    def test_sitemap_file_is_built(self):
        """End to end proof: sphinx run on the generated conf writes sitemap.xml
        with the urls of the handbook under the configured base url"""
        pytest.importorskip('sphinx_sitemap')
        pytest.importorskip('sphinx_rtd_theme')
        batch = self._batch(enable_sitemap=True, subfolder='build')
        batch.step_prepareConfFile()
        sourceDirNode = batch.sourceDirNode
        with sourceDirNode.child('index.rst').open('w') as index_file:
            index_file.write('Handbook\n========\n\nSome content.\n')
        for static_name in ('custom.css', 'custom.js'):
            with sourceDirNode.child('_static/%s' % static_name).open('w') as static_file:
                static_file.write('')
        buildNode = self.app.site.storageNode('site:build', 'html')
        module = gnrImport(os.path.join(self.app.packages['docu'].packageFolder,
                                        'resources', 'tables', 'handbook', 'action',
                                        'export_to_sphinx.py'), avoidDup=True)
        assert module.sphinx_build_main([sourceDirNode.internal_path,
                                         buildNode.internal_path]) == 0
        sitemapNode = buildNode.child('sitemap.xml')
        assert sitemapNode.exists
        with sitemapNode.open('r') as sitemap_file:
            sitemap = sitemap_file.read()
        assert '%s%s/index.html' % (BASE_URL, HANDBOOK_NAME) in sitemap
