"""Tests for the storage layout of the exported handbooks.

A handbook is published in a folder of its own, in the `handbooks` storage when
it is served online and in `local_handbooks` when it is distributed as a zip.
Neither is a folder of the `documentation` storage anymore, which keeps the
attachments and the images of the pages and can therefore be a bucket of its own
without dragging the published html along. The export itself works in a
disposable folder of the page, the only one sphinx is guaranteed to find a
filesystem in, and publishes its build into the handbook folder.
"""
import os
import shutil
import tempfile
from types import SimpleNamespace

import pytest

from gnr.core.gnrlang import gnrImport

from core.common import BaseGnrAppTest
from sitestub import StorageSiteStub, INSTANCE_HOST


class TestDocuHandbookStorage(BaseGnrAppTest):

    @classmethod
    def setup_class(cls):
        super().setup_class()
        cls.db = cls.app.db
        cls.db.model.check(applyChanges=True)
        cls.tbl = cls.db.table('docu.handbook')
        cls.doctbl = cls.db.table('docu.documentation')
        cls.dirs = {name: tempfile.mkdtemp(prefix='gnr_docu_%s_' % name)
                    for name in ('handbooks', 'local_handbooks', 'page')}
        cls.app.site = StorageSiteStub(cls.app, 'docu', cls.dirs)
        cls._makeFixture()

    @classmethod
    def teardown_class(cls):
        for folder in getattr(cls, 'dirs', {}).values():
            shutil.rmtree(folder, ignore_errors=True)
        super().teardown_class()

    @classmethod
    def _makeFixture(cls):
        docroot = dict(name='docroot')
        cls.doctbl.insert(docroot)
        cls.online_id = cls._addHandbook('onlinebook', docroot['id'])
        cls.local_id = cls._addHandbook('localbook', docroot['id'], is_local_handbook=True)
        cls.db.commit()

    @classmethod
    def _addHandbook(cls, name, docroot_id, **kwargs):
        record = dict(name=name, title=name.capitalize(), language='en',
                      docroot_id=docroot_id, **kwargs)
        cls.tbl.insert(record)
        return record['id']

    def _record(self, pkey):
        return self.tbl.record(pkey, virtual_columns='$sphinx_path').output('dict')

    def _batch(self, handbook_id):
        """Batch on the given handbook, up to the folder wiring of pre_process:
        the steps around it need the whole page and a sphinx run."""
        pytest.importorskip('sphinx')
        pytest.importorskip('boto3')
        module_path = os.path.join(self.app.packages['docu'].packageFolder,
                                   'resources', 'tables', 'handbook', 'action',
                                   'export_to_sphinx.py')
        module = gnrImport(module_path, avoidDup=True)
        page = SimpleNamespace(db=self.db, btc=None, site=self.app.site,
                               external_host=INSTANCE_HOST,
                               getUuid=lambda: 'test-batch')
        batch = module.Main(page=page, resource_table=self.tbl)
        batch.zip_urls = []
        batch.handbook_id = handbook_id
        batch.handbook_record = self.tbl.record(handbook_id).output('bag')
        batch.prepareHandbookFolder()
        return batch

    # ------------------------------------------------------------------
    # the handbook folder
    # ------------------------------------------------------------------

    def test_online_handbook_is_published_in_the_handbooks_storage(self):
        assert self._record(self.online_id)['sphinx_path'] == 'handbooks:onlinebook'

    def test_local_handbook_is_published_in_the_local_handbooks_storage(self):
        assert self._record(self.local_id)['sphinx_path'] == 'local_handbooks:localbook'

    def test_storage_node_matches_the_formula_column(self):
        """The formula column is the SQL mirror of handbookStorageNode: the path
        the handbook form shows is the folder the export writes into."""
        for pkey in (self.online_id, self.local_id):
            record = self._record(pkey)
            node = self.tbl.handbookStorageNode(record)
            assert node.fullpath == record['sphinx_path']

    def test_deleting_a_handbook_erases_its_folder(self):
        """Every file of the folder is generated by the export, so the deleted
        handbook leaves nothing behind: the record the trigger receives carries no
        virtual column, hence the path is built from the columns it does carry."""
        pkey = self._addHandbook('goingaway', None)
        self.db.commit()
        published = self.app.site.storageNode('handbooks:goingaway/index.html')
        with published.open('wb') as html_file:
            html_file.write(b'<html>bye</html>')
        assert published.exists
        self.tbl.delete(pkey)
        self.db.commit()
        assert not self.app.site.storageNode('handbooks:goingaway').exists

    # ------------------------------------------------------------------
    # the export batch: work folder and publishing
    # ------------------------------------------------------------------

    def test_sphinx_works_in_a_disposable_folder_of_the_page(self):
        """Sphinx reads and writes through the filesystem, which the storage the
        handbook is published in has not necessarily got: the export works in the
        page folder whatever that storage is, and publishes its build there."""
        batch = self._batch(self.online_id)
        assert batch.publishedDocNode.fullpath == 'handbooks:onlinebook'
        assert batch.sphinxNode.fullpath == 'page:handbook_build/onlinebook/sphinx'
        assert batch.sourceDirNode.fullpath == 'page:handbook_build/onlinebook/sphinx/source'

    def test_the_build_is_published_at_the_root_of_the_handbook_folder(self):
        """publishHandbook promotes the build to the root of the handbook folder
        and drops the sphinx working folder: what is left is the published site."""
        batch = self._batch(self.online_id)
        batch.handbook_url = 'https://docs.example.org/onlinebook/'
        batch.resultNode = batch.sphinxNode.child('build')
        with batch.resultNode.child('index.html').open('wb') as html_file:
            html_file.write(b'<html>built</html>')
        with batch.sourceDirNode.child('index.rst').open('wb') as rst_file:
            rst_file.write(b'built')
        batch.publishHandbook()
        assert self.app.site.storageNode('handbooks:onlinebook/index.html').exists
        assert not self.app.site.storageNode('page:handbook_build/onlinebook/sphinx').exists
        record = self._record(self.online_id)
        assert record['handbook_url'] == batch.handbook_url
        assert record['last_exp_ts']

    def test_the_former_export_is_erased(self):
        """The export regenerates every file of the folder: a page dropped from the
        handbook must not survive in the published site as an orphan."""
        orphan = self.app.site.storageNode('handbooks:onlinebook/gone.html')
        with orphan.open('wb') as html_file:
            html_file.write(b'<html>gone</html>')
        self._batch(self.online_id)
        assert not orphan.exists
