#!/usr/bin/env python
# encoding: utf-8

class Table(object):
    def config_db(self, pkg):
        tbl = pkg.table('handbook', pkey='id', name_long='!!Handbook', 
                        name_plural='!!Handbooks',caption_field='name',audit='lazy')
        self.sysFields(tbl,hierarchical='name',df=True,
                        counter=True,user_ins=True,user_upd=True)
        tbl.column('name',name_long='!!Name', unique=True)
        tbl.column('title',name_long='!!Title')
        tbl.column('docroot_id', size='22', name_long='!!Doc root').relation('documentation.id',
                                                                                relation_name='handbooks',
                                                                                onDelete='setnull',
                                                                                mode='foreignkey')
        tbl.column('toc_roots', name_long='!!Toc roots')
        tbl.column('language',size=':2',name_long='!!Base language').relation('adm.language.code')
        tbl.column('is_local_handbook', dtype='B', name_long='!!Is local handbook')
        tbl.column('local_handbook_zip', name_long='!!Local handbook zip')
        tbl.column('version', name_long='!!Version')
        tbl.column('author', name_long='!!Author')
        tbl.column('theme', name_long='!!Theme')
        tbl.column('handbook_url', name_long='!!Handbook url')
        tbl.column('examples_site',name_long='!!Examples site')
        tbl.column('examples_directory',name_long='!!Examples dir')
        tbl.column('last_exp_ts', dtype='DH', name_long='!!Last export ts')
        tbl.column('custom_styles',name_long='!!Custom styles')
        tbl.column('examples_pars',dtype='X', name_long='!!Examples parameters')
        tbl.column('ogp_image', dtype='P', name_long='!!Handbook preview image')
        
        tbl.formulaColumn('sphinx_path', """CASE WHEN $is_local_handbook THEN 'local_handbooks\\:' || $name 
                          ELSE 'handbooks\\:' || $name END""", name_long='!!Sphinx path')

    def handbookStorageNode(self, record):
        """StorageNode of the folder the handbook is published in.

        Online handbooks live in the `handbooks` storage, the zip of the local ones
        in `local_handbooks`: both default to a folder of the site, as any storage
        that is not configured does, and can be pointed anywhere (typically the
        volume the docs web server publishes) configuring the storage service, with
        no impact on the `documentation` storage the attachments and the images of
        the pages are kept in. The sphinx_path formula column is the SQL mirror of
        this path, shown by the handbook form."""
        storage_name = 'local_handbooks' if record['is_local_handbook'] else 'handbooks'
        return self.db.application.site.storageNode(f'{storage_name}:{record["name"]}')

    def trigger_onDeleted(self, record):
        #every file in the handbook folder is generated by the export: nothing to keep
        self.handbookStorageNode(record).delete()
