name: Create docker images

on:
  push:
    branches: ["docker-ci-integration"]

permissions:
  contents: write
  packages: write

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
         context: ./
         push: true
         tags: ghcr.io/${{ github.repository }}:testing
         platforms: linux/amd64,linux/arm64
         provenance: false
