name: Create docker images

on:
  push:
    branches: ["master", "develop"]

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version
        id: getversion
        run: echo "GENROPY_VERSION=$(sed -n 's/^VERSION = \"\([0-9.]*\)\"/\1/p' gnrpy/gnr/__init__.py)" >> $GITHUB_ENV
      - name: Get branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          
      - name: Build and push main Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./dockerfiles/genropy/Dockerfile
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ env.BRANCH }}:latest, ghcr.io/${{ github.repository }}-${{ env.BRANCH }}:${{ env.GENROPY_VERSION }}
          platforms: linux/amd64,linux/arm64
          provenance: false

